version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./database:/var/lib/grafana/data  # Compartilha o banco de dados SQLite
      - ./database:/database
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    entrypoint:
      - /bin/sh
      - -c
      - |
        grafana-cli plugins install frser-sqlite-datasource
        /run.sh


    networks:
      - viaipe-network

  viaipe-agent:
    build:
      context: ./viaipe-agent
    container_name: viaipe-agent
    volumes:
      - ./database:/database  # Compartilha o banco de dados SQLite
    networks:
      - viaipe-network

networks:
  viaipe-network:
